spring.application.name=telemetry-service

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/microfleet
spring.datasource.username=dev_user
spring.datasource.password=dev_password

# Automatically create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true